name: AreTheTypesWrong
on:
  pull_request:
    branches:
      - main
      - release-*

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@v1

      - name: Run build
        run: npm run build && cd dist; npm pack

      - name: Run AreTheTypesWrong
        id: attw
        run: ./node_modules/.bin/attw ./dist/*.tgz --format ascii > $GITHUB_STEP_SUMMARY
